[log]
  level = "INFO"

[api]
  dashboard = true
  insecure = true

[providers.file]
  filename = "/etc/traefik/dynamic_conf.toml"
  watch = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.myresolver.acme]
  email = "your-email@example.com"
  storage = "acme.json"
  [certificatesResolvers.myresolver.acme.tlsChallenge]