# Generated by Django 5.2.1 on 2025-10-15 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('square_feet', models.IntegerField(blank=True, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('ac', models.BooleanField(default=False)),
                ('ac_type', models.CharField(blank=True, choices=[('central', 'Central'), ('window', 'Window'), ('portable', 'Portable'), ('split', 'Split'), ('none', 'None')], max_length=50)),
                ('heat', models.BooleanField(default=True)),
                ('heat_type', models.CharField(blank=True, choices=[('forced_air', 'Forced Air'), ('radiant', 'Radiant'), ('baseboard', 'Baseboard'), ('heat_pump', 'Heat Pump'), ('boiler', 'Boiler'), ('fireplace', 'Fireplace'), ('stove', 'Stove'), ('none', 'None')], max_length=50)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Home Profile',
                'verbose_name_plural': 'Home Profiles',
            },
        ),
    ]
