# Generated by Django 5.2.1 on 2025-10-15 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_homecomponent_componentimage_componentattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Property Tax', 'Property Tax'), ('Utilities', 'Utilities'), ('Insurance', 'Insurance'), ('Mortgage', 'Mortgage'), ('HOA Documents', 'HOA Documents'), ('Permits', 'Permits'), ('Inspection Reports', 'Inspection Reports'), ('Appraisals', 'Appraisals'), ('Title & Deed', 'Title & Deed'), ('Warranties', 'Warranties'), ('Contracts', 'Contracts'), ('Receipts', 'Receipts'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.IntegerField()),
                ('document_date', models.DateField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=4)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
