# Generated by Django 5.2.1 on 2025-11-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_contractor_maintenancehistory_maintenanceattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeprofile',
            name='heating_source',
            field=models.CharField(blank=True, choices=[('natural_gas', 'Natural Gas'), ('oil', 'Oil'), ('electric', 'Electric'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='homeprofile',
            name='is_septic',
            field=models.BooleanField(default=False, verbose_name='Septic System'),
        ),
        migrations.AlterField(
            model_name='homeprofile',
            name='heat_type',
            field=models.CharField(blank=True, choices=[('forced_air', 'Forced Air'), ('radiant', 'Radiant'), ('baseboard', 'Baseboard'), ('stove', 'Stove')], max_length=50),
        ),
    ]
