# Generated by Django 5.2.1 on 2025-11-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_homeprofile_heating_source_homeprofile_is_septic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='category',
            field=models.CharField(blank=True, choices=[('HVAC', 'HVAC'), ('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('General Maintenance', 'General Maintenance'), ('Landscaping', 'Landscaping'), ('Roofing', 'Roofing'), ('Painting', 'Painting'), ('Carpentry', 'Carpentry'), ('Flooring', 'Flooring'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
