# Generated by Django 5.2.1 on 2025-11-26 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_contractor_category_alter_contractor_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='home_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='owner.homecomponent'),
        ),
    ]
