# Generated by Django 5.2.1 on 2025-12-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0009_task_home_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homeprofile',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='homeprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
