# Generated by Django 5.2.1 on 2025-12-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0013_maintenancehistory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurrence_days_of_month',
            field=models.JSONField(blank=True, default=list, help_text='Selected days of month or relative day pattern for monthly recurrence'),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_days_of_week',
            field=models.JSONField(blank=True, default=list, help_text='Selected days of week for weekly recurrence'),
        ),
    ]
