# Generated by Django 5.2.1 on 2025-12-31 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0016_remove_notification_unique_user_task_notification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Appliances', 'Appliances'), ('HVAC', 'HVAC'), ('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('Roofing', 'Roofing'), ('Windows & Doors', 'Windows & Doors'), ('Flooring', 'Flooring'), ('Gutters', 'Gutters'), ('Water Heater', 'Water Heater'), ('Security System', 'Security System'), ('Garage Door', 'Garage Door'), ('Sump Pump', 'Sump Pump'), ('Other', 'Other')], max_length=50)),
                ('subcategory', models.CharField(blank=True, help_text="More specific type, e.g., 'Furnace', 'Water Heater (Tank)'", max_length=100)),
                ('match_keywords', models.JSONField(blank=True, default=list, help_text='Keywords to match against component name, brand, model')),
                ('match_brands', models.JSONField(blank=True, default=list, help_text='Specific brands this applies to (empty = all brands)')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('importance', models.TextField(blank=True, help_text='Why this maintenance task matters')),
                ('frequency_months', models.IntegerField(help_text='How often this task should be performed (in months)')),
                ('season', models.CharField(choices=[('all', 'All Seasons'), ('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter')], default='all', max_length=20)),
                ('region', models.CharField(choices=[('all', 'All Regions'), ('northeast', 'Northeast'), ('southeast', 'Southeast'), ('midwest', 'Midwest'), ('southwest', 'Southwest'), ('west', 'West'), ('pacific', 'Pacific')], default='all', max_length=20)),
                ('skill_level', models.IntegerField(default=1, help_text='Skill level required (1-5, where 1 is easiest)')),
                ('time_estimate_minutes', models.IntegerField(help_text='Estimated time to complete in minutes')),
                ('tools_needed', models.JSONField(blank=True, default=list)),
                ('safety_warning', models.TextField(blank=True)),
                ('contractor_type', models.CharField(blank=True, help_text='Type of contractor if professional help needed', max_length=100)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost to perform this task', max_digits=10, null=True)),
                ('estimated_deferred_cost', models.CharField(blank=True, help_text="Estimated cost if maintenance is deferred, e.g., '$4,000–$12,000'", max_length=100)),
                ('image_cues', models.TextField(blank=True, help_text='Description of visual cues to identify the component/task')),
                ('symptom_tags', models.JSONField(blank=True, default=list, help_text='User-facing troubleshooting keywords')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'subcategory', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TaskRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_months', models.IntegerField(blank=True, help_text='Override template frequency (null = use template default)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether tasks should be generated from this registration')),
                ('last_task_generated', models.DateField(blank=True, null=True)),
                ('next_task_due', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_registrations', to='owner.homecomponent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_registrations', to=settings.AUTH_USER_MODEL)),
                ('task_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='owner.tasktemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('home_component', 'task_template')},
            },
        ),
    ]
