# Generated by Django 5.2.1 on 2026-01-20 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0017_add_task_template_and_registration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly name like 'Main House' or 'Vacation Home'", max_length=255)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('square_feet', models.IntegerField(blank=True, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('ac', models.BooleanField(default=False)),
                ('ac_type', models.CharField(blank=True, choices=[('central', 'Central'), ('window', 'Window'), ('portable', 'Portable'), ('split', 'Split'), ('none', 'None')], max_length=50)),
                ('heat', models.BooleanField(default=True)),
                ('heat_type', models.CharField(blank=True, choices=[('forced_air', 'Forced Air'), ('radiant', 'Radiant'), ('baseboard', 'Baseboard'), ('stove', 'Stove')], max_length=50)),
                ('heating_source', models.CharField(blank=True, choices=[('natural_gas', 'Natural Gas'), ('oil', 'Oil'), ('electric', 'Electric'), ('other', 'Other')], max_length=50)),
                ('is_septic', models.BooleanField(default=False, verbose_name='Septic System')),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Homes',
                'ordering': ['name', 'address'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='homelocation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homecomponent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_components', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homelocation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenancehistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='owner.home'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractors', to='owner.home'),
        ),
        migrations.AddField(
            model_name='document',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='owner.home'),
        ),
        migrations.AddField(
            model_name='homecomponent',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='owner.home'),
        ),
        migrations.AddField(
            model_name='homelocation',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='owner.home'),
        ),
        migrations.AddField(
            model_name='maintenancehistory',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_histories', to='owner.home'),
        ),
        migrations.AddField(
            model_name='task',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='owner.home'),
        ),
        migrations.AddField(
            model_name='taskregistration',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_registrations', to='owner.home'),
        ),
        migrations.CreateModel(
            name='UserHomeContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='owner.home')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_context', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Home Context',
                'verbose_name_plural': 'User Home Contexts',
            },
        ),
        migrations.CreateModel(
            name='HomeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('viewer', 'Viewer')], default='owner', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text="User's default/primary home")),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='owner.home')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-joined_at'],
                'unique_together': {('user', 'home')},
            },
        ),
    ]
