# Generated by Django 5.0.7 on 2024-07-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_productpurchases'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPurchases',
        ),
    ]
