# Generated by Django 5.0.7 on 2024-07-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_djstripe_workaround'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
