FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ARG PUBLIC_ASTRO_DOMAIN
ARG PUBLIC_STRIPE_PUBLIC_KEY

RUN npm run build

EXPOSE 4321

CMD ["npm", "run", "preview"]