FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ARG PUBLIC_ASTRO_DOMAIN
ARG PUBLIC_STRIPE_PUBLIC_KEY

RUN npm run build

# Install a production-ready static file server
RUN npm install -g serve

EXPOSE 4321

# Serve the built files from the dist directory
CMD ["serve", "-s", "dist", "-l", "4321"]
